-- AlterTable
ALTER TABLE "public"."Doctors" ALTER COLUMN "first_name" DROP NOT NULL,
ALTER COLUMN "last_name" DROP NOT NULL,
ALTER COLUMN "bio" DROP NOT NULL,
ALTER COLUMN "verified" DROP NOT NULL,
ALTER COLUMN "reyting" DROP NOT NULL,
ALTER COLUMN "experience_years" DROP NOT NULL,
ALTER COLUMN "phone" DROP NOT NULL,
ALTER COLUMN "password" DROP NOT NULL,
ALTER COLUMN "date_of_birth" DROP NOT NULL,
ALTER COLUMN "gender" DROP NOT NULL,
ALTER COLUMN "region" DROP NOT NULL;
